export const GET_ORDER_DETAILS = "GET_ORDER_DETAILS";
export const REQUEST_API_DATA = "REQUEST_API_DATA";
export const RECEIVE_API_DATA = "RECEIVE_API_DATA";

export const ASYNC_FETCH = 'ASYNC_FETCH';
export const ASYNC_FETCH_SUCCESS = 'ASYNC_FETCH_SUCCESS';
export const ASYNC_FETCH_FAILURE = 'ASYNC_FETCH_FAILURE';
export const ASYNC_FETCH_INVALIDATE = 'ASYNC_FETCH_INVALIDATE';
export const ERR_RECEIVED = 'ERR_RECEIVED';
export const RESPONSE_RECEIVED = 'RESPONSE_RECEIVED';
export const PAGE_LOAD_API_ERROR = 'PAGE_LOAD_API_ERROR';